Repository KarmaKamikaze/TRACE-Q, pull requests merged in 2024-04, with the labels that each got.

#58 I don't remember what we did
  src/boost-api/CMakeLists.txt
  src/main.cpp
  src/simp-algorithms/TRACE_Q.cpp
  src/trajectory_data_handling/trajectory_sql.cpp
  src/trajectory_data_handling/trajectory_sql.hpp
  tests/CMakeLists.txt
Labels: bug

#60 Boost beast controller and endpoints
  src/boost-api/CMakeLists.txt
  src/boost-api/endpoint_handlers.cpp
  src/boost-api/endpoint_handlers.hpp
  src/data/trajectory_structure.hpp
  src/main.cpp
  src/trajectory_data_handling/trajectory_sql.cpp
  src/trajectory_data_handling/trajectory_sql.hpp
Labels: enhancement

#65 Change insert endpoint
  src/boost-api/Endpoint_Handlers.cpp
  src/trajectory_data_handling/File_Manager.hpp
Labels: enhancement

#63 K-Nearest-Neighbour for query API and query error in TRACE-Q
  src/data/Trajectory.hpp
  src/main.cpp
  src/querying/CMakeLists.txt
  src/querying/KNN_Query.cpp
  src/querying/KNN_Query.hpp
  src/querying/KNN_Query_Test.cpp
  src/querying/KNN_Query_Test.hpp
  src/querying/Range_Query.hpp
  src/querying/Range_Query_Test.hpp
  src/simp-algorithms/TRACE_Q.cpp
  src/simp-algorithms/TRACE_Q.hpp
  src/trajectory_data_handling/File_Manager.cpp
  src/trajectory_data_handling/File_Manager.hpp
  src/trajectory_data_handling/Trajectory_Manager.cpp
  src/trajectory_data_handling/Trajectory_Manager.hpp
Labels: enhancement

#70 Refactored range query to independent class
  src/boost-api/Endpoint_Handlers.cpp
  src/querying/KNN_Query.cpp
  src/querying/KNN_Query.hpp
  src/querying/KNN_Query_Test.hpp
  src/querying/Range_Query.cpp
  src/querying/Range_Query.hpp
  src/simp-algorithms/TRACE_Q.hpp
  src/trajectory_data_handling/File_Manager.cpp
  src/trajectory_data_handling/File_Manager.hpp
  src/trajectory_data_handling/Trajectory_Manager.cpp
Labels: enhancement

#66 Endpoint/handle db range query
  src/boost-api/Endpoint_Handlers.cpp
  src/boost-api/Endpoint_Handlers.hpp
  src/main.cpp
  src/querying/Range_Query.hpp
  src/trajectory_data_handling/Trajectory_Manager.hpp
Labels: enhancement

#73 Created knn query endpoint, fixed naming convention throughout endpoi…
  src/boost-api/Endpoint_Handlers.cpp
  src/boost-api/Endpoint_Handlers.hpp
  src/main.cpp
  src/querying/KNN_Query.hpp
  src/trajectory_data_handling/Trajectory_Manager.cpp
  src/trajectory_data_handling/Trajectory_Manager.hpp
Labels: enhancement

#72 CORS headers and minor tweak to Start_API
  src/boost-api/Endpoint_Handlers.cpp
  src/boost-api/Start_API.cpp
Labels: enhancement

#74 TRACE-Q run-method which runs the algorithm in batches concurrently
  src/main.cpp
  src/simp-algorithms/MRPA.cpp
  src/simp-algorithms/TRACE_Q.cpp
  src/simp-algorithms/TRACE_Q.hpp
  src/trajectory_data_handling/Trajectory_Manager.cpp
  src/trajectory_data_handling/Trajectory_Manager.hpp
Labels: enhancement

#86 Benchmarking
  src/CMakeLists.txt
  src/benchmark/Benchmark.cpp
  src/benchmark/Benchmark.hpp
  src/benchmark/CMakeLists.txt
  src/benchmark/F1.cpp
  src/benchmark/F1.hpp
  src/benchmark/TRACE_Q_Benchmark.cpp
  src/benchmark/benchmark-query-objects/Benchmark_KNN_Query.hpp
  src/benchmark/benchmark-query-objects/Benchmark_Query.hpp
  src/benchmark/benchmark-query-objects/Benchmark_Range_Query.hpp
  src/benchmark/benchmark.hpp
  src/boost-api/Endpoint_Handlers.cpp
  src/main.cpp
  src/querying/KNN_Query_Test.cpp
  src/querying/KNN_Query_Test.hpp
  src/querying/Range_Query.cpp
  src/querying/Range_Query.hpp
  src/querying/Range_Query_Test.hpp
  src/simp-algorithms/TRACE_Q.cpp
  src/simp-algorithms/TRACE_Q.hpp
  src/trajectory_data_handling/File_Manager.cpp
  src/trajectory_data_handling/Trajectory_Manager.cpp
  tests/benchmark_test.cpp
Labels: enhancement, test
